SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View12]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table12];
GO
ALTER AUTHORIZATION
    ON [dbo].[View12]
    TO SCHEMA OWNER;