SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View14]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table14];
GO
ALTER AUTHORIZATION
    ON [dbo].[View14]
    TO SCHEMA OWNER;