SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View53]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table53];
GO
ALTER AUTHORIZATION
    ON [dbo].[View53]
    TO SCHEMA OWNER;