SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View59]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table59];
GO
ALTER AUTHORIZATION
    ON [dbo].[View59]
    TO SCHEMA OWNER;