SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View63]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table63];
GO
ALTER AUTHORIZATION
    ON [dbo].[View63]
    TO SCHEMA OWNER;