SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View49]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table49];
GO
ALTER AUTHORIZATION
    ON [dbo].[View49]
    TO SCHEMA OWNER;