SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View64]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table64];
GO
ALTER AUTHORIZATION
    ON [dbo].[View64]
    TO SCHEMA OWNER;