SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View71]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table71];
GO
ALTER AUTHORIZATION
    ON [dbo].[View71]
    TO SCHEMA OWNER;