SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View37]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table37];
GO
ALTER AUTHORIZATION
    ON [dbo].[View37]
    TO SCHEMA OWNER;