SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View20]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table20];
GO
ALTER AUTHORIZATION
    ON [dbo].[View20]
    TO SCHEMA OWNER;