SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View92]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table92];
GO
ALTER AUTHORIZATION
    ON [dbo].[View92]
    TO SCHEMA OWNER;