SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View88]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table88];
GO
ALTER AUTHORIZATION
    ON [dbo].[View88]
    TO SCHEMA OWNER;