SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View18]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table18];
GO
ALTER AUTHORIZATION
    ON [dbo].[View18]
    TO SCHEMA OWNER;