SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View21]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table21];
GO
ALTER AUTHORIZATION
    ON [dbo].[View21]
    TO SCHEMA OWNER;