SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View44]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table44];
GO
ALTER AUTHORIZATION
    ON [dbo].[View44]
    TO SCHEMA OWNER;