SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View50]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table50];
GO
ALTER AUTHORIZATION
    ON [dbo].[View50]
    TO SCHEMA OWNER;