SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View74]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table74];
GO
ALTER AUTHORIZATION
    ON [dbo].[View74]
    TO SCHEMA OWNER;