SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View80]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table80];
GO
ALTER AUTHORIZATION
    ON [dbo].[View80]
    TO SCHEMA OWNER;