SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View95]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table95];
GO
ALTER AUTHORIZATION
    ON [dbo].[View95]
    TO SCHEMA OWNER;