SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View99]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table99];
GO
ALTER AUTHORIZATION
    ON [dbo].[View99]
    TO SCHEMA OWNER;