SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View41]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table41];
GO
ALTER AUTHORIZATION
    ON [dbo].[View41]
    TO SCHEMA OWNER;