SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View51]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table51];
GO
ALTER AUTHORIZATION
    ON [dbo].[View51]
    TO SCHEMA OWNER;