SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View27]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table27];
GO
ALTER AUTHORIZATION
    ON [dbo].[View27]
    TO SCHEMA OWNER;