SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View24]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table24];
GO
ALTER AUTHORIZATION
    ON [dbo].[View24]
    TO SCHEMA OWNER;