SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View73]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table73];
GO
ALTER AUTHORIZATION
    ON [dbo].[View73]
    TO SCHEMA OWNER;