SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View46]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table46];
GO
ALTER AUTHORIZATION
    ON [dbo].[View46]
    TO SCHEMA OWNER;