SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View10]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table10];
GO
ALTER AUTHORIZATION
    ON [dbo].[View10]
    TO SCHEMA OWNER;