SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View19]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table19];
GO
ALTER AUTHORIZATION
    ON [dbo].[View19]
    TO SCHEMA OWNER;