SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View28]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table28];
GO
ALTER AUTHORIZATION
    ON [dbo].[View28]
    TO SCHEMA OWNER;