SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View65]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table65];
GO
ALTER AUTHORIZATION
    ON [dbo].[View65]
    TO SCHEMA OWNER;