SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View25]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table25];
GO
ALTER AUTHORIZATION
    ON [dbo].[View25]
    TO SCHEMA OWNER;