SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View60]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table60];
GO
ALTER AUTHORIZATION
    ON [dbo].[View60]
    TO SCHEMA OWNER;