SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View22]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table22];
GO
ALTER AUTHORIZATION
    ON [dbo].[View22]
    TO SCHEMA OWNER;