SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View62]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table62];
GO
ALTER AUTHORIZATION
    ON [dbo].[View62]
    TO SCHEMA OWNER;