SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View75]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table75];
GO
ALTER AUTHORIZATION
    ON [dbo].[View75]
    TO SCHEMA OWNER;