SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View89]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table89];
GO
ALTER AUTHORIZATION
    ON [dbo].[View89]
    TO SCHEMA OWNER;