SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View15]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table15];
GO
ALTER AUTHORIZATION
    ON [dbo].[View15]
    TO SCHEMA OWNER;