SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View13]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table13];
GO
ALTER AUTHORIZATION
    ON [dbo].[View13]
    TO SCHEMA OWNER;