SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View52]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table52];
GO
ALTER AUTHORIZATION
    ON [dbo].[View52]
    TO SCHEMA OWNER;