SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View77]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table77];
GO
ALTER AUTHORIZATION
    ON [dbo].[View77]
    TO SCHEMA OWNER;