SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View66]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table66];
GO
ALTER AUTHORIZATION
    ON [dbo].[View66]
    TO SCHEMA OWNER;