SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View83]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table83];
GO
ALTER AUTHORIZATION
    ON [dbo].[View83]
    TO SCHEMA OWNER;