SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View23]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table23];
GO
ALTER AUTHORIZATION
    ON [dbo].[View23]
    TO SCHEMA OWNER;