SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View93]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table93];
GO
ALTER AUTHORIZATION
    ON [dbo].[View93]
    TO SCHEMA OWNER;