SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View30]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table30];
GO
ALTER AUTHORIZATION
    ON [dbo].[View30]
    TO SCHEMA OWNER;