SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View84]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table84];
GO
ALTER AUTHORIZATION
    ON [dbo].[View84]
    TO SCHEMA OWNER;