SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View86]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table86];
GO
ALTER AUTHORIZATION
    ON [dbo].[View86]
    TO SCHEMA OWNER;