SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View100]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table100];
GO
ALTER AUTHORIZATION
    ON [dbo].[View100]
    TO SCHEMA OWNER;