SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View57]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table57];
GO
ALTER AUTHORIZATION
    ON [dbo].[View57]
    TO SCHEMA OWNER;