SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [View32]
AS
SELECT [ID],
       [Name],
       [Value],
       [CreatedDate]
FROM   [Table32];
GO
ALTER AUTHORIZATION
    ON [dbo].[View32]
    TO SCHEMA OWNER;