SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [trg_DatabaseDDL]
    ON DATABASE
    FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
    AS BEGIN
           PRINT 'DDL Trigger fired';
       END
GO
ENABLE TRIGGER [trg_DatabaseDDL] ON DATABASE