SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table68]
AS
BEGIN
    SELECT *
    FROM   [Table68];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table68]
    TO SCHEMA OWNER;