SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table60]
AS
BEGIN
    SELECT *
    FROM   [Table60];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table60]
    TO SCHEMA OWNER;