SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table64]
AS
BEGIN
    SELECT *
    FROM   [Table64];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table64]
    TO SCHEMA OWNER;