SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table71]
AS
BEGIN
    SELECT *
    FROM   [Table71];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table71]
    TO SCHEMA OWNER;