SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table27]
AS
BEGIN
    SELECT *
    FROM   [Table27];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table27]
    TO SCHEMA OWNER;