SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table4]
AS
BEGIN
    SELECT *
    FROM   [Table4];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table4]
    TO SCHEMA OWNER;