SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table35]
AS
BEGIN
    SELECT *
    FROM   [Table35];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table35]
    TO SCHEMA OWNER;