SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table40]
AS
BEGIN
    SELECT *
    FROM   [Table40];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table40]
    TO SCHEMA OWNER;