SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table72]
AS
BEGIN
    SELECT *
    FROM   [Table72];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table72]
    TO SCHEMA OWNER;