SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table28]
AS
BEGIN
    SELECT *
    FROM   [Table28];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table28]
    TO SCHEMA OWNER;