SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table56]
AS
BEGIN
    SELECT *
    FROM   [Table56];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table56]
    TO SCHEMA OWNER;