SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table98]
AS
BEGIN
    SELECT *
    FROM   [Table98];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table98]
    TO SCHEMA OWNER;