SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table89]
AS
BEGIN
    SELECT *
    FROM   [Table89];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table89]
    TO SCHEMA OWNER;