SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table79]
AS
BEGIN
    SELECT *
    FROM   [Table79];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table79]
    TO SCHEMA OWNER;