SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table15]
AS
BEGIN
    SELECT *
    FROM   [Table15];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table15]
    TO SCHEMA OWNER;