SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table10]
AS
BEGIN
    SELECT *
    FROM   [Table10];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table10]
    TO SCHEMA OWNER;