SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table54]
AS
BEGIN
    SELECT *
    FROM   [Table54];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table54]
    TO SCHEMA OWNER;