SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table73]
AS
BEGIN
    SELECT *
    FROM   [Table73];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table73]
    TO SCHEMA OWNER;