SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table69]
AS
BEGIN
    SELECT *
    FROM   [Table69];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table69]
    TO SCHEMA OWNER;