SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table94]
AS
BEGIN
    SELECT *
    FROM   [Table94];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table94]
    TO SCHEMA OWNER;