SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table81]
AS
BEGIN
    SELECT *
    FROM   [Table81];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table81]
    TO SCHEMA OWNER;