SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table48]
AS
BEGIN
    SELECT *
    FROM   [Table48];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table48]
    TO SCHEMA OWNER;