SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table47]
AS
BEGIN
    SELECT *
    FROM   [Table47];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table47]
    TO SCHEMA OWNER;