SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table3]
AS
BEGIN
    SELECT *
    FROM   [Table3];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table3]
    TO SCHEMA OWNER;