SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table75]
AS
BEGIN
    SELECT *
    FROM   [Table75];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table75]
    TO SCHEMA OWNER;