SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table97]
AS
BEGIN
    SELECT *
    FROM   [Table97];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table97]
    TO SCHEMA OWNER;