SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table80]
AS
BEGIN
    SELECT *
    FROM   [Table80];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table80]
    TO SCHEMA OWNER;