SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table77]
AS
BEGIN
    SELECT *
    FROM   [Table77];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table77]
    TO SCHEMA OWNER;