SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table87]
AS
BEGIN
    SELECT *
    FROM   [Table87];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table87]
    TO SCHEMA OWNER;