SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table86]
AS
BEGIN
    SELECT *
    FROM   [Table86];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table86]
    TO SCHEMA OWNER;