SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table22]
AS
BEGIN
    SELECT *
    FROM   [Table22];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table22]
    TO SCHEMA OWNER;