SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table83]
AS
BEGIN
    SELECT *
    FROM   [Table83];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table83]
    TO SCHEMA OWNER;