SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table14]
AS
BEGIN
    SELECT *
    FROM   [Table14];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table14]
    TO SCHEMA OWNER;