SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table34]
AS
BEGIN
    SELECT *
    FROM   [Table34];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table34]
    TO SCHEMA OWNER;