SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table19]
AS
BEGIN
    SELECT *
    FROM   [Table19];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table19]
    TO SCHEMA OWNER;