SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table42]
AS
BEGIN
    SELECT *
    FROM   [Table42];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table42]
    TO SCHEMA OWNER;