SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table25]
AS
BEGIN
    SELECT *
    FROM   [Table25];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table25]
    TO SCHEMA OWNER;