SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table96]
AS
BEGIN
    SELECT *
    FROM   [Table96];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table96]
    TO SCHEMA OWNER;