SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table76]
AS
BEGIN
    SELECT *
    FROM   [Table76];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table76]
    TO SCHEMA OWNER;