SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table52]
AS
BEGIN
    SELECT *
    FROM   [Table52];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table52]
    TO SCHEMA OWNER;