SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table29]
AS
BEGIN
    SELECT *
    FROM   [Table29];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table29]
    TO SCHEMA OWNER;