SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table7]
AS
BEGIN
    SELECT *
    FROM   [Table7];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table7]
    TO SCHEMA OWNER;