SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table13]
AS
BEGIN
    SELECT *
    FROM   [Table13];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table13]
    TO SCHEMA OWNER;