SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table26]
AS
BEGIN
    SELECT *
    FROM   [Table26];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table26]
    TO SCHEMA OWNER;