SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table1]
AS
BEGIN
    SELECT *
    FROM   [Table1];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table1]
    TO SCHEMA OWNER;