SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table39]
AS
BEGIN
    SELECT *
    FROM   [Table39];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table39]
    TO SCHEMA OWNER;