SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table65]
AS
BEGIN
    SELECT *
    FROM   [Table65];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table65]
    TO SCHEMA OWNER;