SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table8]
AS
BEGIN
    SELECT *
    FROM   [Table8];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table8]
    TO SCHEMA OWNER;