SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table51]
AS
BEGIN
    SELECT *
    FROM   [Table51];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table51]
    TO SCHEMA OWNER;