SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table67]
AS
BEGIN
    SELECT *
    FROM   [Table67];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table67]
    TO SCHEMA OWNER;