SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table90]
AS
BEGIN
    SELECT *
    FROM   [Table90];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table90]
    TO SCHEMA OWNER;