SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table99]
AS
BEGIN
    SELECT *
    FROM   [Table99];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table99]
    TO SCHEMA OWNER;