SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table20]
AS
BEGIN
    SELECT *
    FROM   [Table20];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table20]
    TO SCHEMA OWNER;