SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table78]
AS
BEGIN
    SELECT *
    FROM   [Table78];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table78]
    TO SCHEMA OWNER;