SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table50]
AS
BEGIN
    SELECT *
    FROM   [Table50];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table50]
    TO SCHEMA OWNER;