SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table95]
AS
BEGIN
    SELECT *
    FROM   [Table95];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table95]
    TO SCHEMA OWNER;