SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table43]
AS
BEGIN
    SELECT *
    FROM   [Table43];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table43]
    TO SCHEMA OWNER;