SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table91]
AS
BEGIN
    SELECT *
    FROM   [Table91];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table91]
    TO SCHEMA OWNER;