SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table59]
AS
BEGIN
    SELECT *
    FROM   [Table59];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table59]
    TO SCHEMA OWNER;