SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table17]
AS
BEGIN
    SELECT *
    FROM   [Table17];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table17]
    TO SCHEMA OWNER;