SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table61]
AS
BEGIN
    SELECT *
    FROM   [Table61];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table61]
    TO SCHEMA OWNER;