SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table6]
AS
BEGIN
    SELECT *
    FROM   [Table6];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table6]
    TO SCHEMA OWNER;