SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table70]
AS
BEGIN
    SELECT *
    FROM   [Table70];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table70]
    TO SCHEMA OWNER;