SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table12]
AS
BEGIN
    SELECT *
    FROM   [Table12];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table12]
    TO SCHEMA OWNER;