SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table55]
AS
BEGIN
    SELECT *
    FROM   [Table55];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table55]
    TO SCHEMA OWNER;