SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table41]
AS
BEGIN
    SELECT *
    FROM   [Table41];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table41]
    TO SCHEMA OWNER;