SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table30]
AS
BEGIN
    SELECT *
    FROM   [Table30];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table30]
    TO SCHEMA OWNER;