SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Proc_Select_Table88]
AS
BEGIN
    SELECT *
    FROM   [Table88];
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Proc_Select_Table88]
    TO SCHEMA OWNER;