SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ana] (
    [id]      INT          NULL,
    [ime]     VARCHAR (5)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Prezime] VARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY];
GO
ALTER AUTHORIZATION
    ON [dbo].[Ana]
    TO SCHEMA OWNER;