SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_1] (
    [gfgfg]  NCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [gfgfgf] NCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY];
GO
ALTER AUTHORIZATION
    ON [dbo].[Table_1]
    TO SCHEMA OWNER;