SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees] (
    [EmployeeID] INT             IDENTITY (1, 1) NOT NULL,
    [FirstName]  NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [LastName]   NVARCHAR (50)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [HireDate]   DATE            NOT NULL,
    [Salarybre]     DECIMAL (10, 2) NOT NULL,
    PRIMARY KEY CLUSTERED ([EmployeeID] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];
GO
ALTER AUTHORIZATION
    ON [dbo].[Employees]
    TO SCHEMA OWNER;
