SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BigSampleTable](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime2](7) NULL,
	[IsActive] [bit] NULL,
	[Amount] [decimal](18, 2) NULL,
	[Quantity] [int] NULL,
	[Price] [money] NULL,
	[Discount] [float] NULL,
	[Rating] [real] NULL,
	[Status] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Notes] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedBy] [sysname] COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModifiedBy] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedTime] [smalldatetime] NULL,
	[ModifiedTime] [time](7) NULL,
	[Reference] [uniqueidentifier] NULL,
	[BlobData] [varbinary](max) NULL,
	[FileExtension] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhoneNumber] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZipCode] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[State] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Country] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Email] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[URL] [varchar](2083) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Latitude] [float] NULL,
	[Longitude] [float] NULL,
	[BirthDate] [date] NULL,
	[HireDate] [datetimeoffset](7) NULL,
	[Gender] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MaritalStatus] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SSN] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IPAddress] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeviceID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserAgent] [nvarchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Preferences] [xml] NULL,
	[JsonData] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Flag1] [bit] NULL,
	[Flag2] [bit] NULL,
	[Flag3] [bit] NULL,
	[Flag4] [bit] NULL,
	[Count1] [int] NULL,
	[Count2] [bigint] NULL,
	[Count3] [smallint] NULL,
	[Count4] [tinyint] NULL,
	[Temp1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Temp2] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Temp3] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Temp4] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Temp5] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Salary] [smallmoney] NULL,
	[Bonus] [decimal](10, 3) NULL,
	[HoursWorked] [float] NULL,
	[LeaveDays] [int] NULL,
	[PerformanceScore] [int] NULL,
	[ProjectID] [uniqueidentifier] NULL,
	[DepartmentID] [int] NULL,
	[ManagerID] [int] NULL,
	[TeamID] [int] NULL,
	[RoleID] [int] NULL,
	[AccessLevel] [int] NULL,
	[StartTime] [time](7) NULL,
	[EndTime] [time](7) NULL,
	[Shift] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekendAvailability] [bit] NULL,
	[IsRemote] [bit] NULL,
	[RemoteLocation] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Certification] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Degree] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GraduationYear] [int] NULL,
	[GPA] [decimal](4, 2) NULL,
	[SchoolName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmergencyContact] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Relationship] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactNumber] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LanguageSpoken] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SkillLevel] [int] NULL,
	[YearsExperience] [decimal](4, 1) NULL,
	[PreviousCompany] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastPosition] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReasonForLeaving] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RehireEligible] [bit] NULL,
	[LastWorkingDay] [date] NULL,
	[RelocationWilling] [bit] NULL,
	[WorkPermitStatus] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Nationality] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PassportNumber] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VisaExpiryDate] [date] NULL,
	[BackgroundCheck] [bit] NULL,
	[ReferenceContact] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmploymentType] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContractEndDate] [date] NULL,
	[PayrollGroup] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankAccountNumber] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IFSCCode] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TaxIDNumber] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuranceProvider] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyNumber] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
