SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Sales].[Orders] (
    [OrderID]    INT             IDENTITY (1, 1) NOT NULL,
    [CustomerID] INT             NOT NULL,
    [Amount]     DECIMAL (10, 2) NULL,
    [OrderDate]  DATE            NULL,
    PRIMARY KEY CLUSTERED ([OrderID] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];
GO
ALTER AUTHORIZATION
    ON [Sales].[Orders]
    TO SCHEMA OWNER;
GO
ALTER TABLE [Sales].[Orders] WITH CHECK
    ADD FOREIGN KEY ([CustomerID]) REFERENCES [Sales].[Customers] ([CustomerID]);