SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [Func_Square_3]
(@Number DECIMAL (10, 2))
RETURNS DECIMAL (10, 2)
AS
BEGIN
    RETURN @Number * @Number;
END
GO
ALTER AUTHORIZATION
    ON [dbo].[Func_Square_3]
    TO SCHEMA OWNER;